name: AzureDataLabs_AzureSynapse
summary: Terraform example for Lab 1 - Data Analytics with Azure Synapse
description: Deploys an environment using Terraform containing a resource group
runner: Terraform
templatePath: main.tf
parameters: 
- id: "prefix"
  name: "Prefix"
  description: "Prefix Convention to add to all created resources' names"
  type: "string"
  required: true
- id: "postfix"
  name: "Postfix"
  description: "Postfix Convention to add to all created resources' names"
  type: "string"
  required: true
- id: "location"
  name: "Location"
  description: "Azure region to deploy the environment's resources to"
  default: "centralus"
  type: "string"
- id: "enable_private_endpoints"
  name: "enable_private_endpoints"
  default: "false"
  type: "string"
- id: "enable_jumphost"
  name: "enable_jumphost"
  default: "false"
  type: "string"
- id: "enable_analysis_services_server"
  name: "enable_analysis_services_server"
  default: "false"
  type: "string"
- id: "enable_data_factory"
  name: "enable_data_factory"
  default: "false"
  type: "string"
- id: "enable_synapse_sql_pool"
  name: "enable_synapse_sql_pool"
  default: "false"
  type: "string"
- id: "enable_synapse_spark_pool"
  name: "enable_synapse_spark_pool"
  default: "false"
  type: "string"
- id: "enable_event_hub"
  name: "enable_event_hub"
  default: "false"
  type: "string"
