name: FunctionApp
summary: Creates a function app
description: Deploys an environment using Terraform containing a Function App
runner: terraform
templatePath: function_app.tf
parameters: 
- id: "resource_name"
  name: "Resource Name"
  description: "Name of the function app to deploy"
  required: true
  type: "string"
- id: "location"
  name: "Location"
  description: "Azure region the Function App and other resources will deploy to"
  required: true
  type: "string"
- id: "os_type"
  name: "Operating System"
  description: "Operating System the Function App will run on"
  default: "linux"
  type: "string"
- id: "runtime"
  name: "Function Runtime"
  description: "Runtime the Function App will use"
  default: "python"
  type: "string"
