name: choco
command: "./choco.ps1 -Package {{package}} -Version {{version}} {{#if ignoreChecksums}}--ignore-checksums{{/if}}"
inputs:
  package:
    defaultValue: ""
    type: "string"
    required: true
  version:
    defaultValue: ""
    type: "string"
    required: true
  ignoreChecksums:
    defaultValue: false
    type: "boolean"
    required: false
