name: choco
command: "./choco.ps1 -Package {{package}} -Version {{version}}  -ignoreChecksums {{ignore-checksum-error}}"
inputs:
  package:
    defaultValue: ""
    type: "string"
    required: true
  version:
    defaultValue: ""
    type: "string"
    required: true
  ignore-checksum-error:
    defaultValue: false
    type: "boolean"
    required: false
