name: choco
command: "./Choco.ps1 -Package {{package}} -Version {{version}} -IgnoreChecksums {ignoreChecksums}}"
inputs:
  package:
    defaultValue: ""
    type: string
    required: true
  version:
    defaultValue: ""
    type: string
    required: true
  ignoreChecksums:
    defaultValue: false
    type: string
    allowedValues: ["true", "false"]
    required: false